print(f"1 es mayor que 2 --> {1 > 2}")
print(f"1 es menor que 2 --> {1 < 2}")
print(f"1 es mayor o igual que 2 --> {1 >= 2}")
print(f"1 es menor o igual que 2 --> {1 <= 2}")
print(f"2 es mayor o igual que 2 --> {2 >= 2}")
print(f"2 es menor o igual que 2 --> {2 <= 2}")
print(f"2 es igual que 2 --> {2 == 2}")
print(f"2 es igual que 3 --> {2 == 3}")
print(f"2 es igual que \"2\" --> {2 == "2"}")
print(f"2 es disitnto que \"2\" --> {2 != "2"}")
print(f"2 es dintinto que 2 --> {2 != 2}")
print(f"1 es dintinto que 2 --> {1 != 2}")